#!/bin/bash
# Script to add DNS record for audiobook.pandasdroid.shop

echo "🌐 Adding DNS record for Audiobook Speed Calculator"
echo ""
echo "Please add this DNS record in Cloudflare Dashboard:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Dashboard URL: https://dash.cloudflare.com"
echo "Domain: pandasdroid.shop"
echo ""
echo "DNS Record Details:"
echo "  Type:    CNAME"
echo "  Name:    audiobook"
echo "  Target:  6567f05e-dc86-4df0-b031-ed3ddb3049c1.cfargotunnel.com"
echo "  Proxy:   ✅ Enabled (orange cloud)"
echo "  TTL:     Auto"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Once added, your app will be live at:"
echo "👉 https://audiobook.pandasdroid.shop"
echo ""
echo "Status:"
echo "  ✅ Production build running (port 5173)"
echo "  ✅ Cloudflare tunnel active"
echo "  ✅ Code on GitHub: https://github.com/pandasdroid/audiobookspeedcalculator"
echo ""
